import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactNode } from "react";
import "./globals.css";
import styles from "./page.module.css";
import { Providers } from "./providers";
import AppHeader from "components/layouts/app-header/app-header";
import { Sidebar } from "@/components/elements/Sidebar/sidebar";

const geistSans = localFont({
  src: "../styles/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../styles/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <div className="app-shell">
            <Sidebar />
            <div className="app-shell__main">
              <AppHeader />
              <main className="app-content">{children}</main>
              <footer className={styles.footer}>
                <p>© 2025 Serio Fishing Map</p>
              </footer>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
